In [1]:
import pandas as pd
from string import Template
from pathlib import Path
import json

DATA_FILE_GEMMA = Path("data/gemma-multilingual-zero-prompts.csv")
DATA_FILE_QWEN = Path("data/qwen-multilingual-zero-prompts.csv")

In [2]:
qwen_df = pd.read_csv(DATA_FILE_QWEN)
gemma_df = pd.read_csv(DATA_FILE_GEMMA)

In [3]:
marathi_df = gemma_df[gemma_df['language']=="Marathi"].copy().reset_index(drop=True)
sinhala_df = gemma_df[gemma_df['language']=="Sinhala"].copy().reset_index(drop=True)
tamil_df = gemma_df[gemma_df['language']=="Tamil"].copy().reset_index(drop=True)

In [4]:
albanian_df = qwen_df[qwen_df['language']=="Albanian"].copy().reset_index(drop=True)
odia_df = qwen_df[qwen_df['language']=="Odia"].copy().reset_index(drop=True)
hindi_df = qwen_df[qwen_df['language']=="Hindi"].copy().reset_index(drop=True)
punjabi_df = qwen_df[qwen_df['language']=="Punjabi"].copy().reset_index(drop=True)

In [6]:
# Read the Excel file
examples_df = pd.read_excel(
    "data/albania.xlsx"
)

In [8]:

# --------------------------------------------------
# Create numeric grade column
# "Grade 3" -> 3
# "Grade 4" -> 4
# --------------------------------------------------
examples_df["grade"] = (
    examples_df["Grade"]
    .str.extract(r"(\d+)")
    .astype(int)
)

# --------------------------------------------------
# Create topic numbering that resets within each grade
# --------------------------------------------------
examples_df["topic_num"] = (
    examples_df.groupby("grade")
    .cumcount()
    .add(1)
)

# --------------------------------------------------
# Create topic column
# Format:
# 1. Topic : Learning Objectives
# 2. Topic : Learning Objectives
# ...
# --------------------------------------------------
examples_df["topic"] = (
    examples_df["topic_num"].astype(str)
    + ". "
    + examples_df["Topic"].astype(str).str.strip()
    + " : "
    + examples_df["Learning objectives"].astype(str).str.strip()
)

# Optional cleanup
examples_df = examples_df.drop(columns=["topic_num"])

In [10]:

# Create example_1 column
examples_df["example_1"] = examples_df.apply(
    lambda row: json.dumps(
        {
            "question": row["Questions"],
            "answer": row["Answer"]
        },
        ensure_ascii=False
    ) if pd.notna(row["Questions"]) and pd.notna(row["Answer"]) else None,
    axis=1
)

# Optional: remove the temporary columns

In [18]:
examples_df["country"] = "Albania"
examples_df["curriculum"] = "Albanian National"
examples_df["addressing"] = "Albanian"
examples_df["language"] = "Albanian"

In [24]:
examples_df["topic_list"] = (
    examples_df
    .groupby("grade")["topic"]
    .transform(lambda topics: "\n".join(topics.astype(str)))
)

In [39]:
examples_df = examples_df.drop(columns=["Curriculum", "Grade", "Topic", "Learning objectives", "Questions", "Translated Questions", "Answer", "Translated answer"])

In [41]:
examples_df.to_excel(
    "data/albanian.xlsx",
    index=False
)

In [8]:
examples = pd.read_excel(
    "data/india.xlsx",
    sheet_name="Correct_3ver_Final_Updated"
)

examples = examples.rename(columns={"Grade": "grade"})

examples = examples.reset_index(drop=True)

In [9]:


# Create one row per unique grade-topic-learning objective
unique_topics = (
    examples[["grade", "Topic", "Learning Objective"]]
    .drop_duplicates()
    .copy()
)

# Number unique topics within each grade
unique_topics["topic_num"] = (
    unique_topics.groupby("grade")
    .cumcount()
    .add(1)
)

# Merge topic numbers back to all example rows
examples = examples.merge(
    unique_topics,
    on=["grade", "Topic", "Learning Objective"],
    how="left"
)

# Create topic column
examples["topic"] = (
    examples["topic_num"].astype(str)
    + ". "
    + examples["Topic"].astype(str).str.strip()
    + " : "
    + examples["Learning Objective"].astype(str).str.strip()
)

examples = examples.drop(columns=["topic_num"])

In [10]:


# Make sure matching columns have same names/types
examples["grade"] = examples["grade"].astype(int)
hindi_df["grade"] = hindi_df["grade"].astype(int)

examples["topic"] = examples["topic"].astype(str).str.strip()
hindi_df["topic"] = hindi_df["topic"].astype(str).str.strip()

# Create JSON string for each example row
examples["example_json"] = examples.apply(
    lambda row: json.dumps(
        {
            "question": row["Hindi question"],
            "answer": row["Answer_Hindi"]
        },
        ensure_ascii=False
    ),
    axis=1
)



# Number examples within each grade-topic pair
examples["example_num"] = (
    examples.groupby(["grade", "topic"])
    .cumcount()
    .add(1)
)

# Keep only the first 10 examples for each grade-topic pair
examples = examples[examples["example_num"] <= 10].copy()

# Convert example_num to column names
examples["example_col"] = "example_" + examples["example_num"].astype(str)

# Pivot into wide format
examples_wide = examples.pivot_table(
    index=["grade", "topic"],
    columns="example_col",
    values="example_json",
    aggfunc="first"
).reset_index()

examples_wide.columns.name = None

In [24]:
hindi_meta = hindi_df[
    ["country", "curriculum", "addressing", "grade", "topic_list", "language"]
].drop_duplicates(subset=["grade"])

In [26]:
hindi = examples_wide.merge(
    hindi_meta,
    on=["grade"],
    how="left"
)

In [27]:
hindi

,grade,topic,example_1,example_10,example_2,example_3,example_4,example_5,example_6,example_7,example_8,example_9,country,curriculum,addressing,topic_list,language
0,3,1. Counting : reads and writes numbers up to 9...,"{""question"": ""गौरव का रोल नंबर 150 है। गौरव के...","{""question"": ""संख्या 572 में, सैकड़ों के स्थान...","{""question"": ""संख्या 572 में, सैकड़ों के स्थान...","{""question"": ""राहुल का रोल नंबर 299 के बाद है।...","{""question"": ""संख्या 719 में, कौन सा अंक दशकों...","{""question"": ""मैं एक 3-अंकों वाली संख्या हूँ। ...","{""question"": ""संख्या 692 में, सैकड़ों के स्थान...","{""question"": ""सबसे बड़े 3-अंकीय नंबर बनाने के ...","{""question"": ""संख्या 864 में, दस के स्थान पर क...","{""question"": ""स्नेहा का रोल नंबर 26 है। स्नेहा...",India,NCERT,Indian,1. Counting : reads and writes numbers up to 9...,Hindi
1,3,10. measurement of weight : weighs objects usi...,"{""question"": ""तरबूज अनानास से भारी होता है। अन...",NaN,"{""question"": ""एक बिल्ली खरगोश से भारी होती है।...","{""question"": ""एक किताब कापी से भारी होती है। ए...","{""question"": ""एक धातु का बर्तन प्लास्टिक की बा...","{""question"": ""एक आम केले से भारी है। एक केला आ...","{""question"": ""गेहूं की एक बोरी का वजन 50 किलोग...","{""question"": ""चावल का एक थैला 5 किलोग्राम का ह...","{""question"": ""रिया ने 250 ग्राम वज़न का बिस्कि...",NaN,India,NCERT,Indian,1. Counting : reads and writes numbers up to 9...,Hindi
2,3,11. measurement of capacity : compares the cap...,"{""question"": ""एक जग में 3 लीटर पानी आता है। एक...",NaN,"{""question"": ""एक बाल्टी में 10 लीटर पानी आता ह...","{""question"": ""रवि की बोतल में मीना की बोतल से ...","{""question"": ""एक चायदानी में कप से ज़्यादा चाय...","{""question"": ""एक स्टील के बर्तन में 6 कप पानी ...","{""question"": ""आशा एक कप से पानी डालकर अपना फूल...","{""question"": ""सीता एक मग से बाल्टी भरती है। बा...","{""question"": ""रोहन के पास एक जग है जिससे 5 गिल...",NaN,India,NCERT,Indian,1. Counting : reads and writes numbers up to 9...,Hindi
3,3,12. Calendar : identifies a particular day and...,"{""question"": ""आज 10 जनवरी है। भारत में गणतंत्र...","{""question"": ""रिया ने 15 मई को अपनी गर्मियों क...","{""question"": ""दिल्ली में एक स्कूल 15 मई को गर्...","{""question"": ""अमित का जन्मदिन 02/04/2015 को है...","{""question"": ""अनिल का जन्मदिन 6/7/2015 को है। ...","{""question"": ""रिया का स्कूल दिवाली के लिए 1 नव...","{""question"": ""एक विज्ञान प्रदर्शनी 5 जनवरी से ...","{""question"": ""इस साल रक्षाबंधन 19 अगस्त को है।...","{""question"": ""एक क्रिकेट टूर्नामेंट 10 दिसंबर ...","{""question"": ""रिया की अंतिम परीक्षाएं 4 मार्च ...",India,NCERT,Indian,1. Counting : reads and writes numbers up to 9...,Hindi
4,3,13. time : reads the time correctly to the hou...,"{""question"": ""राहुल ने शाम को 4:30 बजे अपना अभ...","{""question"": ""मीना ने पूर्वाह्न 10:20 बजे पेंट...","{""question"": ""एक फुटबॉल मैच अपराह्न 3:20 बजे श...","{""question"": ""एक केक को अपराह्न 2:10 बजे ओवन म...","{""question"": ""स्कूल की प्रार्थना सभा पूर्वाह्न...","{""question"": ""कुणाल ने अपराह्न 6:10 बजे खेलना ...","{""question"": ""अर्जुन पूर्वाह्न 7:45 बजे स्कूल ...","{""question"": ""नेहा ने अपराह्न 3:15 बजे खेलना श...","{""question"": ""रमेश ने अपराह्न 2:10 बजे किताब प...","{""question"": ""सीता ने अपराह्न 5:30 बजे खाना बन...",India,NCERT,Indian,1. Counting : reads and writes numbers up to 9...,Hindi
5,3,14. Pattern : extends patterns in numbers,"{""question"": ""रिया आमों को एक पैटर्न में सजा र...","{""question"": ""अनुपस्थित संख्या भरें:\n90, 80, ...","{""question"": ""योग करने वाले छात्रों की संख्या ...","{""question"": ""एक श्रेणी 9 का पहाड़ा दिखाती है:...","{""question"": ""एक बिंदु पैटर्न इस तरह बढ़ता है:...","{""question"": ""एक रेलवे कोच नंबर का पैटर्न इस प...","{""question"": ""रानी लड्डूओं को एक पैटर्न में सज...","{""question"": ""मोहन पूजा के लिए फूल लगा रहा है:...","{""question"": ""एक पैटर्न हर बार 5 से घटता है: ...","{""question"": ""डोमिनो शैली का डॉट पैटर्न बढ़ता ...",India,NCERT,Indian,1. Counting : reads and writes numbers up to 9...,Hindi
6,3,2. Compare numbers : compares numbers up to 99...,"{""question"": ""सबसे छोटा नंबर लिखें: 562, 625, ...","{""question"": ""एक क्रिकेट मैच में, भारत ने 447 ...","{""question"": ""सबसे बड़ा नंबर लिखें: 709, 970, ...","{""question"": ""912, 921, और 129 में सबसे बड़ा न...","{""question"": ""इस समूह में सबसे छोटा नंबर लिखें...","{""question"": ""संख्याओं को सबसे छोटी से सबसे बड...","{""question"": ""सांख्यिकाओं को सबसे बड़े से सबसे...","{""question"": ""रिया के पास ₹ 324 हैं, और उसके भ...","{""question"": ""दिल्ली की एक दुकान ने सोमवार को ...","{""question"": ""एक बस ने सुबह 375 यात्री और शाम ...",India,NCERT,Indian,1. Counting : reads and writes numbers up to 9...,Hindi
7,3,3. addition : solves simple daily life problem...,"{""question"": ""एक पुस्तकालय में 124 कहानी की कि...","{""question"": ""एक किसान ने पहले हफ्ते में 275 क...","{""question"": ""रवि ने पिछले साल 78 टिकटें एकत्र...","{""question"": ""एक स्कूल समारोह में 135 लड़के और...","{""question"": ""एक फल विक्रेता ने सुबह 67 सेब और...","{""question"": ""एक बस में सुबह 42 यात्री और दोपह...","{""question"": ""एक किसान ने एक खेत से 93 किलोग्र...","{""question"": ""एक क्रिकेट मैच में, टीम A ने पहल...","{""question"": ""रीना ने सुबह समुद्र तट पर 48 सीप...","{""question"": ""प्रिया ने सोमवार को एक किताब के ...",India,NCERT,Indian,1. Counting : reads and writes numbers up to 9...,Hindi
8,3,4. subtraction : solves simple daily life prob...,"{""question"": ""एक फल विक्रेता के पास 120 सेब थे...","{""question"": ""एक स्कूल में 180 छात्र थे। 65 छा...","{""question"": ""प्रिया के पास 92 कैंडी थीं। उसने...","{""question"": ""एक पुस्तकालय में 250 पुस्तकें थी...","{""question"": ""अर्जुन ने 134 टिकटें इकट्ठी कीं।...","{""question"": ""रोहन के पास ₹ 275 थे। उसने ₹ 138...","{""question"": ""एक फल विक्रेता के पास सुबह 342 स...","{""question"": ""एक स्कूल पुस्तकालय में 450 किताब...","{""question"": ""सीता के पास हार बनाने के लिए 325...","{""question"": ""एक किसान के पास 500 किलोग्राम चा...",India,NCERT,Indian,1. Counting : reads and writes numbers up to 9...,Hindi
9,3,5. addition and subtraction : solves simple da...,"{""question"": ""रवि ने एक दुकान से 78 और दूसरी द...","{""question"": ""एक कंपनी ने 480 मेजें बनाई। उसने...","{""question"": ""नेहा के पास 120 चॉकलेट थीं। उसने...","{""question"": ""प्रिया ने ₹120, ₹135, ₹150 और ₹1...","{""question"": ""एक फल विक्रेता के पास 180 सेब थे...","{""question"": ""एक दुकानदार के पास 300 पेंसिलें ...","{""question"": ""राज के पास ₹ 250 थे। उसने ₹135 क...","{""question"": ""एक दुकानदार के पास 400 किलोग्राम...","{""question"": ""एक स्कूल में 320 छात्र थे। 85 छा...","{""question"": ""मीना के पास 180 पेंसिल थीं। उसने...",India,NCERT,Indian,1. Counting : reads and writes numbers up to 9...,Hindi
10,3,6. multiplication : constructs and uses the mu...,"{""question"": ""सीमा के पास 4 फोटो एलबम हैं। प्र...","{""question"": ""एक बेकरी रोज़ 14 पैकेट बिस्कुट ब...","{""question"": ""अमित ने क्रेयॉन के 3 पैकेट खरीदे...","{""question"": ""कक्षा में कुर्सियों की 6 पंक्तिय...","{""question"": ""प्रिया के पास 7 जार हैं। प्रत्ये...","{""question"": ""रवि ने टमाटर के पौधों की 5 पंक्त...","{""question"": ""एक डिब्बे में 6 खिलौना कारें हैं...","{""question"": ""अमन के पास 6 डिब्बे हैं। प्रत्ये...","{""question"": ""एक शिक्षक ने कक्षा में 8 कतारों ...","{""question"": ""एक बगीचे में 12 गमले हैं। प्रत्य...",India,NCERT,Indian,1. Counting : reads and writes numbers up to 9...,Hindi
11,3,7. division : explains the meaning of division...,"{""question"": ""रवि के पास 24 आम हैं। वह उन्हें ...","{""question"": ""एक शिक्षक के पास 48 पेंसिल हैं। ...","{""question"": ""एक शिक्षिका के पास 30 चॉकलेट हैं...","{""question"": ""18 पेंसिलें हैं जिन्हें 3 बक्सों...","{""question"": ""रोहन के पास 42 कंचे हैं। वह उन्ह...","{""question"": ""एक फल विक्रेता के पास 36 सेब हैं...","{""question"": ""मीना के पास 20 चूड़ियाँ हैं। वह ...","{""question"": ""24 लड्डू बराबर-बराबर बक्सों में ...","{""question"": ""एक कार्टन में जूस की 30 बोतलें ह...","{""question"": ""रवि के पास 40 टॉफियाँ हैं। वह उन...",India,NCERT,Indian,1. Counting : reads and writes numbers up to 9...,Hindi
12,3,8. fraction : represents the fractions as half...,"{""question"": ""अमन के पास 10 सेब हैं। उसने उनमे...","{""question"": ""रवि के पास 7 पतंगें हैं, और सोहम...","{""question"": ""रिया के पास 14 पेंसिलें हैं। उसन...","{""question"": ""एक टोकरी में 20 आम हैं। राज ने उ...","{""question"": ""मीना के पास 18 टॉफियाँ थीं। उसने...","{""question"": ""एक डिब्बे में 12 क्रेयॉन हैं। रव...","{""question"": ""सीमा ने 16 कुकीज़ बनाईं। उसने उन...","{""question"": ""रोहन के पास 5 पेंसिलें हैं, और म...","{""question"": ""अमन के पास 4 चॉकलेट हैं, और राहु...","{""question"": ""प्रिया के पास 6 कहानी की किताबें...",India,NCERT,Indian,1. Counting : reads and writes numbers up to 9...,Hindi
13,3,9. measurement of length : estimates and measu...,"{""question"": ""नेहा की किताब 4 हाथ लंबी है। उसक...",NaN,"{""question"": ""एक मेज़ 8 हाथ लंबी है, एक बेंच 6...","{""question"": ""एक साड़ी 20 हाथ लंबी है, एक दुपट...","{""question"": ""एक रस्सी मापने वाली फीते से लंबी...","{""question"": ""एक ट्रेन बस से लंबी है। बस कार स...","{""question"": ""एक शेल्फ 6 हाथ लंबी है। उसके नीच...","{""question"": ""विक्रम अपने कदमों से दो कक्षा की...","{""question"": ""लिविंग रूम में एक चटाई 7 हाथ लंब...",NaN,India,NCERT,Indian,1. Counting : reads and writes numbers up to 9...,Hindi
14,4,1. addition : solves simple daily life problem...,"{""question"": ""दिल्ली के एक पुस्तकालय में 2,467...",NaN,"{""question"": ""एक किसान ने पहले महीने में 4,135...","{""question"": ""एक स्कूल मेले में शनिवार को 7,29...","{""question"": ""एक डाकघर ने सुबह 3,651 और शाम को...","{""question"": ""एक दुकानदार ने सुबह ₹8,042 और शा...","{""question"": ""एक शहर के दो स्कूलों में क्रमशः ...","{""question"": ""एक ट्रेन ने पहले हफ्ते में 5,891...","{""question"": ""एक अस्पताल ने जनवरी में 7,480 और...",NaN,India,NCERT,Indian,1. addition : solves simple daily life problem...,Hindi
15,4,10. time : relates to 24 hr clock with respect...,"{""question"": ""रिया की ट्रेन अपराह्न 3:45 बजे र...",NaN,"{""question"": ""एक फ़िल्म अपराह्न 7:30 बजे शुरू ...","{""question"": ""एक हवाई जहाज़ 18:20 बजे लैंड करत...","{""question"": ""दिल्ली में मेट्रो 20:10 पर आती ह...","{""question"": ""मुंबई से एक ट्रेन अपराह्न 11:20 ...","{""question"": ""टीवी पर क्रिकेट मैच 18:45 बजे शु...","{""question"": ""टीवी पर बच्चों का एक शो 17:25 पर...","{""question"": ""मुस्कान अपनी डांस क्लास में अपरा...",NaN,India,NCERT,Indian,1. addition : solves simple daily life problem...,Hindi
16,4,11. data handling : represents the collected i...,"{""question"": ""रिया अपनी कक्षा के बच्चों का पसं...","{""question"": ""कक्षा में एक सर्वेक्षण के दौरान,...","{""question"": ""जुलाई के महीने में पाँच छात्रों ...","{""question"": ""विद्यालय के वार्षिक खेल दिवस के ...","{""question"": ""राहुल के पिता एक डेयरी की दुकान ...","{""question"": ""अनीता अपने स्कूल कैंटीन में अलग-...","{""question"": ""एक स्कूल में 5 दिनों के लिए एक प...","{""question"": ""एक अंतर-विद्यालय कला प्रतियोगिता...","{""question"": ""शहर स्तर पर विज्ञान प्रश्नोत्तरी...","{""question"": ""एक पशु आश्रय गृह ने एक महीने में...",India,NCERT,Indian,1. addition : solves simple daily life problem...,Hindi
17,4,2. subtraction : solves simple daily life prob...,"{""question"": ""एक स्कूल ने 5,432 परीक्षा पत्र छ...","{""question"": ""एक किसान के पास 6,700 किलोग्राम ...","{""question"": ""आपको निम्नलिखित संख्या युग्म दिए...","{""question"": ""पिछले साल एक स्कूल में 6,250 छात...","{""question"": ""एक दुकानदार के पास ₹9,300 थे। उस...","{""question"": ""दिल्ली के एक स्कूल में 5,438 छात...","{""question"": ""नोएडा की एक खिलौना फैक्ट्री ने ज...","{""question"": ""भारतीय रेलवे के एक क्षेत्र में 8...","{""question"": ""पंजाब के एक किसान ने इस साल 8,04...","{""question"": ""हरियाणा के एक गोदाम से चावल लेकर...",India,NCERT,Indian,1. addition : solves simple daily life problem...,Hindi
18,4,3. multiplication : multiplies 2 and 3 digit n...,"{""question"": ""एक फल विक्रेता एक दिन में 18 सेब...","{""question"": ""एक ट्रक 175 बोरी चावल ले जा सकता...","{""question"": ""एक किसान के पास 28 आम के पेड़ है...","{""question"": ""एक स्कूल में 125 बेंच हैं। प्रत्...","{""question"": ""एक किसान ने आम के 132 कतारों में...","{""question"": ""एक किताब प्रकाशक ने हर बैच में 2...","{""question"": ""एक निर्माण कार्यकर्ता एक पंक्ति ...","{""question"": ""एक कपड़ा मिल रोज़ 326 मीटर कपड़ा...","{""question"": ""एक बस में 45 सीटें हैं। यदि 12 ब...","{""question"": ""एक सब्जी विक्रेता एक दिन में 34 ...",India,NCERT,Indian,1. addition : solves simple daily life problem...,Hindi
19,4,4. division : divides a number by another numb...,"{""question"": ""एक स्कूल में 864 छात्र हैं। यदि ...","{""question"": ""एक स्कूल में 240 छात्र हैं और उन...","{""question"": ""एक किसान के पास 432 सेब हैं। वह ...","{""question"": ""438 बच्चे स्कूल ट्रिप पर जा रहे ...","{""question"": ""एक थोक व्यापारी के पास 502 किलोग...","{""question"": ""एक फैक्ट्री एक दिन में 252 खिलौन...","{""question"": ""एक ट्रक में 432 किलोग्राम चावल ह...","{""question"": ""एक फैक्ट्री 4,50 बिस्कुट बनाती ह...","{""question"": ""रीता के पास ₹ 200 हैं, जो सभी ₹ ...","{""question"": ""एक किताबों की दुकान को 1,80 पेन ...",India,NCERT,Indian,1. addition : solves simple daily life problem...,Hindi
20,4,5. fraction : finds the number corresponding t...,"{""question"": ""एक फलवाले के पास 90 सेब हैं। उसन...","{""question"": ""एक टोकरी में 60 आम हैं। उनमें से...","{""question"": ""एक केक को 5 बराबर हिस्सों में बा...","{""question"": ""एक पानी की टंकी में 90 लीटर पानी...","{""question"": ""एक टोकरी में 45 आम हैं। नेहा ने ...","{""question"": ""एक बेकरी ने 30 केक बनाए। एक ग्रा...","{""question"": ""एक कक्षा में 60 सीटें हैं। उनमें...","{""question"": ""एक डिब्बे में 40 चॉकलेट हैं। राह...","{""question"": ""आशा ने रात के खाने के लिए 12 रोट...","{""question"": ""एक तरबूज का वजन 9 किलोग्राम है। ...",India,NCERT,Indian,1. addition : solves simple daily life problem...,Hindi
21,4,6. measurement : solves problem involving dail...,"{""question"": ""10 मिलीलीटर की खुराक वाले कप को ...","{""question"": ""कक्षा के ब्लैकबोर्ड का किनारा 30...","{""question"": ""10 मिलीलीटर की कितनी खुराक वाले ...","{""question"": ""एक फैक्ट्री 500 मिलीलीटर जूस की ...","{""question"": ""एक 500 ग्राम चीनी के पैकेट को सं...","{""question"": ""10 किलोग्राम में 500 ग्राम के कि...","{""question"": ""यदि दाल के एक पैकेट का वजन 250 ग...","{""question"": ""यदि एक रबड़ का वजन 10 ग्राम है, ...","{""question"": ""250 ग्राम चावल के पैकेट का वजन क...","{""question"": ""एक दुकान प्रत्येक पैकेट में 100 ...",India,NCERT,Indian,1. addition : solves simple daily life problem...,Hindi
22,4,7. measurement of length : converts metre into...,"{""question"": ""एक शेल्फ 3 मीटर लंबा है। राजू 25...","{""question"": ""एक छड़ी की लंबाई 5 मीटर है, और उ...","{""question"": "" राम और शाम की ऊँचाई एक समान है ...","{""question"": ""एक बोर्ड की लंबाई 2 मीटर है। सोन...","{""question"": ""एक रस्सी 5 मीटर लंबी है। यदि प्र...","{""question"": ""एक रस्सी 20 मीटर लंबी है। एक बढ़...","{""question"": ""एक दर्जी को एक पर्दा बनाने के लि...","{""question"": ""नेहा अपने पिता को लकड़ी के तख्ते...","{""question"": ""एक रिबन 95 सेंटीमीटर लंबा है। इस...","{""question"": ""एक कपड़ा 345 सेंटीमीटर लंबा है। ...",India,NCERT,Indian,1. addition : solves simple daily life problem...,Hindi
23,4,8. time : calculates time intervals/ duration ...,"{""question"": ""घंटे की सुई 6 पर है। पुनः 6 पर प...",NaN,"{""question"": ""एक रेलगाड़ी पूर्वाह्न 9:45 बजे स...","{""question"": ""सीमा ने अपराह्न 6:00 बजे फिल्म द...","{""question"": ""रिया ने दिल्ली से पूर्वाह्न 7:45...","{""question"": ""स्नेहा का स्कूल पूर्वाह्न 9:15 ब...","{""question"": ""एक फुटबॉल मैच अपराह्न 4:45 बजे श...","{""question"": ""रवि पूर्वाह्न 7:30 बजे स्कूल के ...","{""question"": ""अनीता ने अपराह्न 3:20 बजे अपनी क...",NaN,India,NCERT,Indian,1. addition : solves simple daily life problem...,Hindi
24,4,9. time : reads clock time in hour and minutes...,"{""question"": ""एक घंटे के एक चौथाई (¼) में कितन...",NaN,"{""question"": ""एक संगीत का पाठ 45 मिनट तक चलता ...","{""question"": ""रिया के दादाजी हर पूर्वाह्न 6:00...","{""question"": ""प्रिया अपराह्न 4:00 बजे ट्यूशन क...","{""question"": ""अमन पूर्वाह्न 7:15 बजे नाश्ता कर...","{""question"": ""अनन्या पूर्वाह्न 11:00 बजे अपनी ...","{""question"": ""एक कहानी सुनाने का सत्र अपराह्न ...","{""question"": ""मीरा अपराह्न 4:30 बजे पढ़ना शुरू...",NaN,India,NCERT,Indian,1. addition : solves simple daily life problem...,Hindi
25,5,1. fraction : identifies and forms equivalent ...,"{""question"": ""मीना ने एक रिबन को 8 बराबर हिस्स...",NaN,"{""question"": ""5/10 के समतुल्य अंश की पहचान करे...","{""question"": ""अर्जुन ने सुबह अपनी कहानी की कित...","{""question"": ""निम्नलिखित भिन्नों में से कौन सी...","{""question"": ""रिया ने दोसा का 2/4 हिस्सा खाया।...","{""question"": ""सान्या ने अपने क्राफ्ट के लिए रि...","{""question"": ""एक ट्रेन ने यात्रा का 8/16 पूरा ...","{""question"": ""कौन सा भिन्न 4/16 के बराबर है?\n...","{""question"": ""इनमें से कौन सा 9/12 के बराबर है...",India,NCERT,Indian,1. fraction : identifies and forms equivalent ...,Hindi
26,5,10. multiplication : Multiply 3-digit numbers ...,"{""question"": ""कानपुर की एक फैक्ट्री हर दिन 125...","{""question"": ""एक साइकिल फैक्ट्री 135 साइकिलों ...","{""question"": ""एक किसान एक खेत में 132 पौधे लगा...","{""question"": ""एक प्रिंटिंग प्रेस अपने 312 ग्रा...","{""question"": ""एक कपड़ा मिल की एक मशीन एक दिन म...","{""question"": ""महाराष्ट्र में एक आम के बाग में ...","{""question"": ""एक डेयरी किसान 1 किग्रा पनीर ₹28...","{""question"": ""एक स्कूल ने नए सत्र के लिए 425 न...","{""question"": ""एक मिठाई की दुकान 1 ट्रे में 108...","{""question"": ""एक पुस्तक मेला में 312 स्टॉल हैं...",India,NCERT,Indian,1. fraction : identifies and forms equivalent ...,Hindi
27,5,11. division : divides a given number by anoth...,"{""question"": ""एक किसान के पास 1,248 सेब हैं। व...","{""question"": ""एक प्रिंटिंग प्रेस ने 9,856 पोस्...","{""question"": ""एक स्कूल पुस्तकालय में 3,672 कित...","{""question"": ""एक किसान ने 3,648 किलोग्राम गेहू...","{""question"": ""एक किसान ने 2,850 किलोग्राम गेहू...","{""question"": ""चेन्नई के एक स्कूल को 4,824 किता...","{""question"": ""एक किसान ने 6,372 आम तोड़े और उन...","{""question"": ""एक ट्रस्ट ₹ 8,400 की छात्रवृत्ति...","{""question"": ""एक प्रकाशक ने 4,752 किताबें छापी...","{""question"": ""एक क्रिकेट स्टेडियम में 5,280 सी...",India,NCERT,Indian,1. fraction : identifies and forms equivalent ...,Hindi
28,5,2. fraction : compares fractions,"{""question"": ""रवि और मोहन ने जलेबियों की एक प्...",NaN,"{""question"": ""आशा ने अवकाश के दौरान अपनी पानी ...","{""question"": ""स्कूल में लंच के दौरान, प्रिया न...","{""question"": ""एक लड्डू बनाने की प्रतियोगिता मे...","{""question"": ""दो कक्षाओं ने एक स्वच्छता अभियान...","{""question"": ""खो-खो खेलते समय, टीम A ने एक श्र...","{""question"": ""एक कला कक्षा में, वीर ने एक मंडल...","{""question"": ""दो कक्षाओं ने एक स्वच्छता अभियान...",NaN,India,NCERT,Indian,1. fraction : identifies and forms equivalent ...,Hindi
29,5,3. fraction : solves problems on daily life si...,"{""question"": ""आयशा ने सुबह 1/3 लीटर और शाम को ...",NaN,"{""question"": ""एक दुकानदार ने चॉकलेट के एक बार ...","{""question"": ""मीना के पास 2 मीटर लंबा एक रिबन ...","{""question"": ""एक बाल्टी में 20 लीटर पानी आ सकत...","{""question"": ""शनाया ने शनिवार को अपनी किताब का...","{""question"": ""एक क्रिकेट मैच के दौरान, विराज न...","{""question"": ""रितिका अपनी ट्यूशन तक पहुंचने के...","{""question"": ""रिया ने एक बोतल का 7/10 भाग नींब...",NaN,India,NCERT,Indian,1. fraction : identifies and forms equivalent ...,Hindi

In [29]:
hindi.to_excel(
    "data/hindi.xlsx",
    index=False
)

In [30]:
examples = pd.read_excel(
    "data/india.xlsx",
    sheet_name="Correct_3ver_Final_Updated"
)

examples = examples.rename(columns={"Grade": "grade"})

examples = examples.reset_index(drop=True)

In [31]:


# Create one row per unique grade-topic-learning objective
unique_topics = (
    examples[["grade", "Topic", "Learning Objective"]]
    .drop_duplicates()
    .copy()
)

# Number unique topics within each grade
unique_topics["topic_num"] = (
    unique_topics.groupby("grade")
    .cumcount()
    .add(1)
)

# Merge topic numbers back to all example rows
examples = examples.merge(
    unique_topics,
    on=["grade", "Topic", "Learning Objective"],
    how="left"
)

# Create topic column
examples["topic"] = (
    examples["topic_num"].astype(str)
    + ". "
    + examples["Topic"].astype(str).str.strip()
    + " : "
    + examples["Learning Objective"].astype(str).str.strip()
)

examples = examples.drop(columns=["topic_num"])

In [32]:


# Make sure matching columns have same names/types
examples["grade"] = examples["grade"].astype(int)
marathi_df["grade"] = marathi_df["grade"].astype(int)

examples["topic"] = examples["topic"].astype(str).str.strip()
marathi_df["topic"] = marathi_df["topic"].astype(str).str.strip()

# Create JSON string for each example row
examples["example_json"] = examples.apply(
    lambda row: json.dumps(
        {
            "question": row["Marathi Question"],
            "answer": row["Answer Marathi"]
        },
        ensure_ascii=False
    ),
    axis=1
)



# Number examples within each grade-topic pair
examples["example_num"] = (
    examples.groupby(["grade", "topic"])
    .cumcount()
    .add(1)
)

# Keep only the first 10 examples for each grade-topic pair
examples = examples[examples["example_num"] <= 10].copy()

# Convert example_num to column names
examples["example_col"] = "example_" + examples["example_num"].astype(str)

# Pivot into wide format
examples_wide = examples.pivot_table(
    index=["grade", "topic"],
    columns="example_col",
    values="example_json",
    aggfunc="first"
).reset_index()

examples_wide.columns.name = None

In [33]:
marathi_meta = marathi_df[
    ["country", "curriculum", "addressing", "grade", "topic_list", "language"]
].drop_duplicates(subset=["grade"])

marathi = examples_wide.merge(
    marathi_meta,
    on=["grade"],
    how="left"
)

In [35]:
marathi.to_excel(
    "data/marathi.xlsx",
    index=False
)

In [39]:
examples = pd.read_excel(
    "data/india.xlsx",
    sheet_name="Correct_3ver_Final_Updated"
)

examples = examples.rename(columns={"Grade": "grade"})

examples = examples.reset_index(drop=True)

In [40]:


# Create one row per unique grade-topic-learning objective
unique_topics = (
    examples[["grade", "Topic", "Learning Objective"]]
    .drop_duplicates()
    .copy()
)

# Number unique topics within each grade
unique_topics["topic_num"] = (
    unique_topics.groupby("grade")
    .cumcount()
    .add(1)
)

# Merge topic numbers back to all example rows
examples = examples.merge(
    unique_topics,
    on=["grade", "Topic", "Learning Objective"],
    how="left"
)

# Create topic column
examples["topic"] = (
    examples["topic_num"].astype(str)
    + ". "
    + examples["Topic"].astype(str).str.strip()
    + " : "
    + examples["Learning Objective"].astype(str).str.strip()
)

examples = examples.drop(columns=["topic_num"])

In [41]:


# Make sure matching columns have same names/types
examples["grade"] = examples["grade"].astype(int)
odia_df["grade"] = odia_df["grade"].astype(int)

examples["topic"] = examples["topic"].astype(str).str.strip()
odia_df["topic"] = odia_df["topic"].astype(str).str.strip()

# Create JSON string for each example row
examples["example_json"] = examples.apply(
    lambda row: json.dumps(
        {
            "question": row["Odia question"],
            "answer": row["Answer_Odia"]
        },
        ensure_ascii=False
    ),
    axis=1
)



# Number examples within each grade-topic pair
examples["example_num"] = (
    examples.groupby(["grade", "topic"])
    .cumcount()
    .add(1)
)

# Keep only the first 10 examples for each grade-topic pair
examples = examples[examples["example_num"] <= 10].copy()

# Convert example_num to column names
examples["example_col"] = "example_" + examples["example_num"].astype(str)

# Pivot into wide format
examples_wide = examples.pivot_table(
    index=["grade", "topic"],
    columns="example_col",
    values="example_json",
    aggfunc="first"
).reset_index()

examples_wide.columns.name = None

In [42]:
odia_meta = odia_df[
    ["country", "curriculum", "addressing", "grade", "topic_list", "language"]
].drop_duplicates(subset=["grade"])

odia = examples_wide.merge(
    odia_meta,
    on=["grade"],
    how="left"
)

In [44]:
odia.to_excel(
    "data/odia.xlsx",
    index=False
)

In [45]:
examples = pd.read_excel(
    "data/india.xlsx",
    sheet_name="Correct_3ver_Final_Updated"
)

examples = examples.rename(columns={"Grade": "grade"})

examples = examples.reset_index(drop=True)

In [46]:


# Create one row per unique grade-topic-learning objective
unique_topics = (
    examples[["grade", "Topic", "Learning Objective"]]
    .drop_duplicates()
    .copy()
)

# Number unique topics within each grade
unique_topics["topic_num"] = (
    unique_topics.groupby("grade")
    .cumcount()
    .add(1)
)

# Merge topic numbers back to all example rows
examples = examples.merge(
    unique_topics,
    on=["grade", "Topic", "Learning Objective"],
    how="left"
)

# Create topic column
examples["topic"] = (
    examples["topic_num"].astype(str)
    + ". "
    + examples["Topic"].astype(str).str.strip()
    + " : "
    + examples["Learning Objective"].astype(str).str.strip()
)

examples = examples.drop(columns=["topic_num"])

In [47]:


# Make sure matching columns have same names/types
examples["grade"] = examples["grade"].astype(int)
punjabi_df["grade"] = punjabi_df["grade"].astype(int)

examples["topic"] = examples["topic"].astype(str).str.strip()
punjabi_df["topic"] = punjabi_df["topic"].astype(str).str.strip()

# Create JSON string for each example row
examples["example_json"] = examples.apply(
    lambda row: json.dumps(
        {
            "question": row["punjabi question"],
            "answer": row["Answer_punjabi"]
        },
        ensure_ascii=False
    ),
    axis=1
)



# Number examples within each grade-topic pair
examples["example_num"] = (
    examples.groupby(["grade", "topic"])
    .cumcount()
    .add(1)
)

# Keep only the first 10 examples for each grade-topic pair
examples = examples[examples["example_num"] <= 10].copy()

# Convert example_num to column names
examples["example_col"] = "example_" + examples["example_num"].astype(str)

# Pivot into wide format
examples_wide = examples.pivot_table(
    index=["grade", "topic"],
    columns="example_col",
    values="example_json",
    aggfunc="first"
).reset_index()

examples_wide.columns.name = None

In [48]:
punjabi_meta = punjabi_df[
    ["country", "curriculum", "addressing", "grade", "topic_list", "language"]
].drop_duplicates(subset=["grade"])

punjabi = examples_wide.merge(
    punjabi_meta,
    on=["grade"],
    how="left"
)

In [50]:
punjabi.to_excel(
    "data/punjabi.xlsx",
    index=False
)

In [8]:
examples = pd.read_excel(
    "data/lanka.xlsx",
    sheet_name="Sri Lankan - Final",
    dtype={"answer_sinhala": str}
)
examples = examples.rename(columns={"topic": "Topic"})

examples["question_sinhala"] = examples["question_sinhala"].astype("string")
examples["question_sinhala_corrected"] = examples["question_sinhala_corrected"].astype("string")
examples["answer_sinhala"] = examples["answer_sinhala"].astype("string")
examples["question_tamil"] = examples["question_tamil"].astype("string")
examples["answer_tamil"] = examples["answer_tamil"].astype("string")

examples = examples.reset_index(drop=True)

In [13]:
examples = examples[
    examples["answer_sinhala"].notna() &
    (examples["answer_sinhala"].str.strip() != "")
].copy()

In [14]:


# Create one row per unique grade-topic-learning objective
unique_topics = (
    examples[["grade", "Topic", "learning_objective"]]
    .drop_duplicates()
    .copy()
)

examples["selected_question_sinhala"] = (
    examples["question_sinhala_corrected"]
    .fillna(examples["question_sinhala"])
)


# Number unique topics within each grade
unique_topics["topic_num"] = (
    unique_topics.groupby("grade")
    .cumcount()
    .add(1)
)

# Merge topic numbers back to all example rows
examples = examples.merge(
    unique_topics,
    on=["grade", "Topic", "learning_objective"],
    how="left"
)

# Create topic column
examples["topic"] = (
    examples["topic_num"].astype(str)
    + ". "
    + examples["Topic"].astype(str).str.strip()
    + " : "
    + examples["learning_objective"].astype(str).str.strip()
)

examples = examples.drop(columns=["topic_num"])

In [16]:


# Make sure matching columns have same names/types
examples["grade"] = examples["grade"].astype(int)

examples["topic"] = examples["topic"].astype(str).str.strip()

# Create JSON string for each example row
examples["example_json"] = examples.apply(
    lambda row: json.dumps(
        {
            "question": row["selected_question_sinhala"],
            "answer": row["answer_sinhala"]
        },
        ensure_ascii=False
    ),
    axis=1
)



# Number examples within each grade-topic pair
examples["example_num"] = (
    examples.groupby(["grade", "topic"])
    .cumcount()
    .add(1)
)

# Keep only the first 10 examples for each grade-topic pair
examples = examples[examples["example_num"] <= 10].copy()

# Convert example_num to column names
examples["example_col"] = "example_" + examples["example_num"].astype(str)

In [18]:
# Pivot into wide format
examples_wide = examples.pivot_table(
    index=["grade", "topic"],
    columns="example_col",
    values="example_json",
    aggfunc="first"
).reset_index()

examples_wide.columns.name = None

In [20]:
sinhala_df

,UUID,country,curriculum,addressing,grade,topic,topic_list,zeroshot_prompt,language,multilingual_prompt
0,85b31eea-c83e-424f-91a2-132aecc56480,Sri Lanka,Sri Lankan National,Sri Lankan,3,1. Number Concept : Identify the place value o...,1. Number Concept : Identify the place value o...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
1,56df3b80-76dc-4fe5-b227-a29b26611bda,Sri Lanka,Sri Lankan National,Sri Lankan,3,2. Number Concept : Write the number names for...,1. Number Concept : Identify the place value o...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
2,9d3a5dc5-7530-4bea-b3c8-c30d362b50d2,Sri Lanka,Sri Lankan National,Sri Lankan,3,3. Number Concept : Arrange any three numbers ...,1. Number Concept : Identify the place value o...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
3,e45b66a7-4292-4f38-8ef5-6aa99c5c3e4d,Sri Lanka,Sri Lankan National,Sri Lankan,3,4. Number Concept : Identify the greatest or s...,1. Number Concept : Identify the place value o...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
4,35b2b6bd-d4a6-4fb8-853b-40f6149c0106,Sri Lanka,Sri Lankan National,Sri Lankan,3,5. Number Concept : Construct number sequences...,1. Number Concept : Identify the place value o...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
5,39a4fd36-3682-49b1-8f29-dfbda831c580,Sri Lanka,Sri Lankan National,Sri Lankan,3,6. Mathematical Operations : Add two numbers t...,1. Number Concept : Identify the place value o...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
6,a3e0f607-1cb0-4124-9c65-58cdbad13942,Sri Lanka,Sri Lankan National,Sri Lankan,3,7. Mathematical Operations : Subtract one numb...,1. Number Concept : Identify the place value o...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
7,ac09af15-360c-4068-a12c-f4962f56fe5a,Sri Lanka,Sri Lankan National,Sri Lankan,3,8. Mathematical Operations : Multiply a number...,1. Number Concept : Identify the place value o...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
8,9fca92c8-98d2-4b66-b97f-433266a1441d,Sri Lanka,Sri Lankan National,Sri Lankan,3,9. Mathematical Operations : Divide a number n...,1. Number Concept : Identify the place value o...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
9,e1e10f86-35e4-4534-bbe1-5b43e72b29d2,Sri Lanka,Sri Lankan National,Sri Lankan,3,10. Mathematical Operations : Use the names of...,1. Number Concept : Identify the place value o...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
10,5d838ab3-ca4b-44f3-868c-b5340749082f,Sri Lanka,Sri Lankan National,Sri Lankan,3,11. Mathematical Operations : Identify and use...,1. Number Concept : Identify the place value o...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
11,cf4ec730-3b1e-48dc-a8b6-ca3a662f2327,Sri Lanka,Sri Lankan National,Sri Lankan,3,12. Money : Engage in simple money transactions,1. Number Concept : Identify the place value o...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
12,9ea626c2-6e1c-4e89-9076-be224b597374,Sri Lanka,Sri Lankan National,Sri Lankan,4,1. Number Concept : Identify the place value o...,1. Number Concept : Identify the place value o...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
13,753d9495-c456-4d41-9843-b489d05c6af4,Sri Lanka,Sri Lankan National,Sri Lankan,4,2. Number Concept : Write the number names for...,1. Number Concept : Identify the place value o...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
14,0e28ae2f-c848-40d1-918c-75bcdc5623d8,Sri Lanka,Sri Lankan National,Sri Lankan,4,3. Number Concept : Arrange any three numbers ...,1. Number Concept : Identify the place value o...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
15,9167a6bb-7aef-4def-8a69-53867d5eaaa9,Sri Lanka,Sri Lankan National,Sri Lankan,4,4. Number Concept : Identify the greatest or s...,1. Number Concept : Identify the place value o...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
16,f92aea81-fc49-44b6-904c-43dce1684c3e,Sri Lanka,Sri Lankan National,Sri Lankan,4,5. Number Concept : Construct number sequences...,1. Number Concept : Identify the place value o...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
17,358c6b27-4b75-4a4f-af65-1c95d500f6d6,Sri Lanka,Sri Lankan National,Sri Lankan,4,6. Number Concept : Represent halves and quart...,1. Number Concept : Identify the place value o...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
18,f4de7171-f60f-4ea7-a66f-ed2ad66413ad,Sri Lanka,Sri Lankan National,Sri Lankan,4,7. Number Concept : Recognize and use Roman nu...,1. Number Concept : Identify the place value o...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
19,375ec547-35e6-4331-9a29-df2564f29a47,Sri Lanka,Sri Lankan National,Sri Lankan,4,8. Mathematical Operations : Add two or three ...,1. Number Concept : Identify the place value o...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
20,7a9f7ae1-8b29-4b00-9204-1389edfd664f,Sri Lanka,Sri Lankan National,Sri Lankan,4,9. Mathematical Operations : Subtract one numb...,1. Number Concept : Identify the place value o...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
21,6da71440-201b-4437-9b23-a6609f5f9c5c,Sri Lanka,Sri Lankan National,Sri Lankan,4,10. Mathematical Operations : Multiply a numbe...,1. Number Concept : Identify the place value o...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
22,ce070a24-3af0-4459-ba05-af347cc1774d,Sri Lanka,Sri Lankan National,Sri Lankan,4,11. Mathematical Operations : Divide a number ...,1. Number Concept : Identify the place value o...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
23,2e60a6b2-0a20-4e93-bd08-96f91d8c1e71,Sri Lanka,Sri Lankan National,Sri Lankan,4,12. Measurements : Solve basic problems involv...,1. Number Concept : Identify the place value o...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
24,db228d6b-9a6e-4837-b86a-ecffed6e3994,Sri Lanka,Sri Lankan National,Sri Lankan,4,13. Measurements : Perform addition and subtra...,1. Number Concept : Identify the place value o...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
25,cc415a63-4fdd-4c59-9ce9-7ef45ac4070e,Sri Lanka,Sri Lankan National,Sri Lankan,4,14. Measurements : Solve basic problems involv...,1. Number Concept : Identify the place value o...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
26,81cad937-50de-4310-b14c-8aa14b955d89,Sri Lanka,Sri Lankan National,Sri Lankan,4,15. Measurements : Perform addition and subtra...,1. Number Concept : Identify the place value o...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
27,167a421f-5449-4500-8188-cc004235816e,Sri Lanka,Sri Lankan National,Sri Lankan,4,16. Measurements : Solve basic problems involv...,1. Number Concept : Identify the place value o...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
28,59de003e-478c-45b5-810f-90a9701c57c2,Sri Lanka,Sri Lankan National,Sri Lankan,4,17. Measurements : Perform addition and subtra...,1. Number Concept : Identify the place value o...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
29,0540cec7-1b00-4d50-a922-3a47d2158dff,Sri Lanka,Sri Lankan National,Sri Lankan,4,18. Measurements : Identify and use the relati...,1. Number Concept : Identify the place value o...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
30,40d46d9c-c8f9-4ef8-b06a-409fe57e3250,Sri Lanka,Sri Lankan National,Sri Lankan,4,19. Measurements : Perform basic transactions ...,1. Number Concept : Identify the place value o...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
31,27f75c3d-76a3-4872-b24d-f8fe95dc0e39,Sri Lanka,Sri Lankan National,Sri Lankan,4,20. Measurements : Solve problems involving th...,1. Number Concept : Identify the place value o...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
32,ba4a6305-4542-4f08-8f21-996ee4c7461c,Sri Lanka,Sri Lankan National,Sri Lankan,5,1. Numbers : Identify the place value of digit...,1. Numbers : Identify the place value of digit...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
33,19e36715-923c-4c2a-951a-31f9f6a14c26,Sri Lanka,Sri Lankan National,Sri Lankan,5,2. Numbers : Write the number names for number...,1. Numbers : Identify the place value of digit...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
34,1ff3aadd-5e00-4882-af70-57cf36c1fb33,Sri Lanka,Sri Lankan National,Sri Lankan,5,3. Numbers : Arrange any three numbers up to 9...,1. Numbers : Identify the place value of digit...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
35,91957aff-e91a-4a57-a4f4-c87404f6b5ec,Sri Lanka,Sri Lankan National,Sri Lankan,5,4. Numbers : Construct number sequences with t...,1. Numbers : Identify the place value of digit...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
36,9cc13d7e-1d4c-47b4-9f9b-065bb72cd845,Sri Lanka,Sri Lankan National,Sri Lankan,5,5. Numbers : Construct number sequences with t...,1. Numbers : Identify the place value of digit...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
37,239774ce-f74c-43fd-8c45-8dd03356c194,Sri Lanka,Sri Lankan National,Sri Lankan,5,"6. Numbers : Represent halves, quarters, and t...",1. Numbers : Identify the place value of digit...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
38,65d1a924-1744-46df-9f4e-694509f318d2,Sri Lanka,Sri Lankan National,Sri Lankan,5,7. Numbers : Recognize and use Roman numerals ...,1. Numbers : Identify the place value of digit...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
39,ea6c3520-be35-4729-8d50-547179389138,Sri Lanka,Sri Lankan National,Sri Lankan,5,8. Numbers : Recognize tenths in the decimal f...,1. Numbers : Identify the place value of digit...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
40,98557fac-65b3-44f8-a187-b377e425b20a,Sri Lanka,Sri Lankan National,Sri Lankan,5,9. Mathematical Operations : Add numbers that ...,1. Numbers : Identify the place value of digit...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
41,5faffd0f-a7aa-4d5c-86a3-dbd6614f942c,Sri Lanka,Sri Lankan National,Sri Lankan,5,10. Mathematical Operations : Subtract one num...,1. Numbers : Identify the place value of digit...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
42,dba9f5d8-46e9-4224-931d-7c6ee4a1ccdb,Sri Lanka,Sri Lankan National,Sri Lankan,5,11. Mathematical Operations : Multiply a numbe...,1. Numbers : Identify the place value of digit...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
43,c53dc8c9-2f11-47f8-a173-ba634e9eb0b3,Sri Lanka,Sri Lankan National,Sri Lankan,5,12. Mathematical Operations : Divide a number ...,1. Numbers : Identify the place value of digit...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
44,67a38df0-e456-4ce4-862c-3a960dcc015d,Sri Lanka,Sri Lankan National,Sri Lankan,5,13. Mathematical Operations : Solve simple pro...,1. Numbers : Identify the place value of digit...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
45,42498938-2ac7-4f86-a2cf-59d5a055412d,Sri Lanka,Sri Lankan National,Sri Lankan,5,14. Mathematical Operations : Solve simple pro...,1. Numbers : Identify the place value of digit...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
46,a91e31f5-f305-4bd1-9d00-ac010755e8ab,Sri Lanka,Sri Lankan National,Sri Lankan,5,15. Measurements : Solve problems involving ki...,1. Numbers : Identify the place value of digit...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
47,6b0bd166-a316-4c42-924b-1bea37749a2d,Sri Lanka,Sri Lankan National,Sri Lankan,5,16. Measurements : Solve simple calculation pr...,1. Numbers : Identify the place value of digit...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
48,fe4af8aa-d9e4-426b-84a0-8efad2a08623,Sri Lanka,Sri Lankan National,Sri Lankan,5,17. Measurements : Solve basic problems involv...,1. Numbers : Identify the place value of digit...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
49,fa6311d3-666e-4e22-905e-79dac8101f57,Sri Lanka,Sri Lankan National,Sri Lankan,5,18. Measurements : Solve basic problems involv...,1. Numbers : Identify the place value of digit...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
50,2b6d96f1-dd67-42fe-82f6-9683b064b587,Sri Lanka,Sri Lankan National,Sri Lankan,5,19. Measurements : Solve problems involving ca...,1. Numbers : Identify the place value of digit...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
51,89b92f95-4eb3-4763-bb1f-bc0ae5a9fbfb,Sri Lanka,Sri Lankan National,Sri Lankan,5,20. Money : Perform simple money-related calcu...,1. Numbers : Identify the place value of digit...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...
52,f3b60dfc-ef18-4799-b5d1-c06f9eb0de6a,Sri Lanka,Sri Lankan National,Sri Lankan,5,21. Money : Solve problems involving bills,1. Numbers : Identify the place value of digit...,Your task is to create exactly one math word p...,Sinhala,Your task is to create exactly one math word p...

In [21]:
examples_wide["country"] = "Sri Lanka"
examples_wide["curriculum"] = "Sri Lankan National"
examples_wide["addressing"] = "Sri Lankan"
examples_wide["language"] = "Sinhala"

In [23]:
examples_wide["topic_list"] = (
    examples_wide
    .groupby("grade")["topic"]
    .transform(lambda topics: "\n".join(topics.astype(str)))
)

In [24]:
examples_wide

,grade,topic,example_1,example_10,example_2,example_3,example_4,example_5,example_6,example_7,example_8,example_9,country,curriculum,addressing,language,topic_list
0,3,1. Number Concept : Identify the place value o...,"{""question"": ""567 යන සංඛ්‍යාවේ 5න් නිරූපණය වන ...","{""question"": ""123 යන සංඛ්‍යාවේ 1 හි ස්ථානීය අග...","{""question"": ""80 තුළ දහයේ ඒවා කීයක් තිබේද?"", ""...","{""question"": ""දහයේ ඒවා දෙකක් සහ එකේ ඒවා හයක් ඇ...","{""question"": ""135 විහිදුවා ලියන්න"", ""answer"": ...","{""question"": ""2, 5, 7 යන අංක භාවිතා කර සෑදිය හ...","{""question"": ""678 අංකයේ 6 හි ස්ථානීය අගය කුමක්...","{""question"": ""90 තුළ දහයේ ඒවා කීයක් තිබේද?"", ""...","{""question"": ""දහයේ ඒවා 7ක් සහ එකේ ඒවා 8ක් ඇති ...","{""question"": ""236 විහිදුවා ලියන්න."", ""answer"":...",Sri Lanka,Sri Lankan National,Sri Lankan,Sinhala,1. Number Concept : Identify the place value o...
1,3,10. Mathematical Operations : Use the names of...,"{""question"": ""සතියේ පළමු දිනය කුමක්ද?\n"", ""ans...","{""question"": ""වෙසක් උත්සවය යෙදෙන්නේ කුමන මාසයේ...","{""question"": ""වසරේ අවසාන මාසය කුමක්ද?"", ""answe...","{""question"": ""ජනවාරි මාසයේ දින කීයක් තිබේද?"", ...","{""question"": ""වසරකට මාස කීයක් තිබේද?"", ""answer...","{""question"": ""සතියකට දින කීයක් තිබේද?"", ""answe...","{""question"": ""දෙසැම්බර් මාසයේ දින කීයක් තිබේද?...","{""question"": ""අපි සිංහල සහ හින්දු අලුත් අවුරුද...","{""question"": ""වසරේ පළමු මාසය කුමක්ද?"", ""answer...","{""question"": ""අපි නිදහස් දිනය සමරන්නේ කුමන මාස...",Sri Lanka,Sri Lankan National,Sri Lankan,Sinhala,1. Number Concept : Identify the place value o...
2,3,11. Mathematical Operations : Identify and use...,"{""question"": ""බදාදාට පසු දිනය කුමක්ද?"", ""answe...","{""question"": ""අප්‍රේල් සහ ජූනි අතර ඇති මාසය කු...","{""question"": ""අද සඳුදා නම්, දින දෙකකට පසුව එන ...","{""question"": ""අද සිකුරාදා නම්, දින තුනකට පෙර ත...","{""question"": ""සති දෙකකට දින කීයක් තිබේද?"", ""an...","{""question"": ""මාර්තු 5ට සතියකින් පසුව එන දිනය ...","{""question"": ""මැයි 1 බදාදා නම්, මැයි 8 කුමන දි...","{""question"": ""දින 14කට සති කීයක් තිබේද?"", ""ans...","{""question"": ""අගෝස්තු මාසයට මාස තුනකට පසුව එන ...","{""question"": ""ජනවාරි 15 අඟහරුවාදා නම්, ජනවාරි ...",Sri Lanka,Sri Lankan National,Sri Lankan,Sinhala,1. Number Concept : Identify the place value o...
3,3,12. Money : Engage in simple money transactions,"{""question"": ""පැන්සලක මිල රු. 13 කි. අනිල් ළඟ ...","{""question"": ""කඩයක් පෑනක් රුපියල් 20කට, පොතක් ...","{""question"": ""පැපොල් ගෙඩියක් රුපියල් 45කි. එම ...","{""question"": ""අමල් රුපියල් 5 කාසියක් සහ රුපියල...","{""question"": ""දුරියන් ගෙඩියක් රුපියල් 200කි. ම...","{""question"": ""භාජනයක් රුපියල් 22කි. පියල් රුපි...","{""question"": ""ස්ටිකරයක් රුපියල් 13ක්, ඔප දැමූ ...","{""question"": ""චොකලට් එකක් රුපියල් 62කි. රාණි ළ...","{""question"": ""අම්මා රුපියල් 5 කාසි දෙකක් සහ රු...","{""question"": ""අඹ ගෙඩියක් රුපියල් 10ක්, පේර ගෙඩ...",Sri Lanka,Sri Lankan National,Sri Lankan,Sinhala,1. Number Concept : Identify the place value o...
4,3,2. Number Concept : Write the number names for...,"{""question"": ""166 හි සංඛ්‍යා නාමය ලියන්න."", ""a...","{""question"": ""එක්සිය දහනවය' සංඛ්‍යාංකයක් ලෙස ල...","{""question"": ""137 හි සංඛ්‍යා නාමය ලියන්න."", ""a...","{""question"": ""294 හි සංඛ්‍යා නාමය ලියන්න."", ""a...","{""question"": ""154 හි සංඛ්‍යා නාමය ලියන්න."", ""a...","{""question"": ""345 හි සංඛ්‍යා නාමය ලියන්න."", ""a...","{""question"": ""471 හි සංඛ්‍යා නාමය ලියන්න."", ""a...","{""question"": ""පන්සිය විසිහය' සංඛ්‍යාංකයක් ලෙස ...","{""question"": ""තුන්සිය හතළිස් දෙක' සංඛ්‍යාංකයක්...","{""question"": ""හත්සිය අසූ හය' සංඛ්‍යාංකයක් ලෙස ...",Sri Lanka,Sri Lankan National,Sri Lankan,Sinhala,1. Number Concept : Identify the place value o...
5,3,3. Number Concept : Arrange any three numbers ...,"{""question"": ""ක්‍රීඩා උළෙලකදී, නෙළුම් නිවාසය ල...","{""question"": ""බේකරියක් එක් සතියක් තුළ කේක් 675...","{""question"": ""ප්‍රශ්න විචාරාත්මක තරගයකදී රෝස ක...","{""question"": ""පසුගිය මාසය තුළ A කඩය භාණ්ඩ 245ක...","{""question"": ""ක්‍රිකට් තරගයකදී, පළවෙනි ක්‍රීඩක...","{""question"": ""වීර විද්‍යාලයට පොත් 825ක්, ගැමුණ...","{""question"": ""මුද්දර එකතු කිරීමේ තරගයකදී, නිල්...","{""question"": ""A පන්තියේ පොත් 498ක් ද, B පන්තිය...","{""question"": ""ගම්මාන තුනක ජනගහනය 835, 792, සහ ...","{""question"": ""පහත අංක කුඩාම සංඛ්‍යාවේ සිට විශා...",Sri Lanka,Sri Lankan National,Sri Lankan,Sinhala,1. Number Concept : Identify the place value o...
6,3,4. Number Concept : Identify the greatest or s...,"{""question"": ""සිසුන් තිදෙනෙකු ලබාගත් විභාග ලකු...","{""question"": ""614 ට වඩා 2කින් විශාල අංකය කුමක්...","{""question"": ""සීතා, ෆාතිමා සහ ගීතා සිප්පි කටු ...","{""question"": ""නෙළුම් පන්තිය, ඕලු පන්තිය සහ මාන...","{""question"": ""ක්‍රීඩාවක ක්‍රීඩකයන් තිදෙනෙකුගේ ...","{""question"": ""175 ට පෙර එන අංකය කුමක්ද?"", ""ans...","{""question"": ""මිතුරන් තිදෙනෙකු සිප්පි කටු එකතු...","{""question"": ""400 ට වඩා 1ක් අඩු අංකය කුමක්ද?"",...","{""question"": ""ගණිත පරීක්ෂණයකදී, නිමල් ලකුණු 64...","{""question"": ""මෙම අංක තුනෙන් විශාලතම අංකය කුමක...",Sri Lanka,Sri Lankan National,Sri Lankan,Sinhala,1. Number Concept : Identify the place value o...
7,3,5. Number Concept : Construct number sequences...,"{""question"": ""1, 3, 5, ..., ... යන සංඛ්‍යා රටා...","{""question"": ""පහත අංක රටාවේ හිස්තැන් පුරවන්න: ...","{""question"": ""පහත අංක රටාවේ ඊළඟ අංක දෙක ලියන්න...","{""question"": ""පහත අංක රටාවේ ඊළඟ අංක තුන ලියන්න...","{""question"": ""පහත අංක රටාව ආරම්භ වන අංක දෙක ලි...","{""question"": ""පහත අංක රටාවේ හිස්තැන් පුරවන්න: ...","{""question"": ""පහත අංක රටාවේ හිස් වූ අංක ලියන්න...","{""question"": ""පහත අංක රටාවේ ඊළඟ අංක තුන ලියන්න...","{""question"": ""පහත අංක රටාවේ ඊළඟ අංක දෙක ලියන්න...","{""question"": ""පහත අංක රටාව ආරම්භ වන අංක දෙක ලි...",Sri Lanka,Sri Lankan National,Sri Lankan,Sinhala,1. Number Concept : Identify the place value o...
8,3,6. Mathematical Operations : Add two numbers t...,"{""question"": ""පළමු පේළියේ කොඩි 154ක් ඇත. දෙවන ...","{""question"": ""එක් දුම්රියක මගීන් 543ක් සහ තවත්...","{""question"": ""එක් කූඩයක ඇපල් 248ක් සහ තවත් කූඩ...","{""question"": ""කඩයක් සඳුදා පෑන් 312ක් සහ අඟහරුව...","{""question"": ""පාසල් පුස්තකාලයේ පොත් 415ක් සහ ප...","{""question"": ""ගොවිපළක එක් පොකුණක තාරාවන් 527ක්...","{""question"": ""වෙළඳසැලක එක් ගබඩාවක පුටු 316ක් ස...","{""question"": ""උදෑසන වැඩමුරයේ සිසුන් 444ක් සහ ස...","{""question"": ""තැපැල් කාර්යාලය සිකුරාදා ලිපි 32...","{""question"": ""අමල් පසුගිය වසරේ රෝස පඳුරු 215ක්...",Sri Lanka,Sri Lankan National,Sri Lankan,Sinhala,1. Number Concept : Identify the place value o...
9,3,7. Mathematical Operations : Subtract one numb...,"{""question"": ""පංතියක සිසුන් 99ක් සිටිති. ඉන් ස...","{""question"": ""76 සහ 35 අතර වෙනස කුමක්ද?"", ""ans...","{""question"": ""සමන්මලී සතුව ස්ටිකර් 75ක් ඇත. ඇය...","{""question"": ""උද්‍යානයක මල් 88ක් තිබේ. මල් 44ක...","{""question"": ""පොත් රාක්කයක පොත් 62ක් තිබේ. පොත...","{""question"": ""ගොවියාට එළදෙනුන් 95ක් සිටී. එළදෙ...","{""question"": ""පැන්සල් පෙට්ටියක පැන්සල් 84ක් ති...","{""question"": ""බස් රථයක මගීන් 67ක් සිටී. මගීන් ...","{""question"": ""මේසය මත ඇපල් 59ක් තිබේ. ඇපල් 12ක...","{""question"": ""පාසලක පිරිමි ළමුන් 90ක් සිටිති. ...",Sri Lanka,Sri Lankan National,Sri Lankan,Sinhala,1. Number Concept : Identify the place value o...
10,3,8. Mathematical Operations : Multiply a number...,"{""question"": ""එක් ගසක කුරුල්ලන් 4ක් සිටී නම්, ...","{""question"": ""පන්තියක මේස 8ක් තිබේ. පන්ති 5ක ම...","{""question"": ""එක් පේළියක පුටු 6ක් තිබේ. පේළි 5...","{""question"": ""කඩයක් එක් පෙට්ටියක කෝප්ප 7ක් අලෙ...","{""question"": ""මල් බඳුනක මල් 33ක් තිබේ. මල් බඳු...","{""question"": ""කූඩයක ඇපල් 8ක් තිබේ. කූඩ 2ක ඇපල්...","{""question"": ""එක් පැකට්ටුවක පැන්සල් 4ක් තිබේ. ...","{""question"": ""රාක්කයක බෝතල් 44ක් තිබේ. රාක්ක 2...","{""question"": ""ගොවියෙක් එක් පේළියක ගස් 6ක් සිටු...","{""question"": ""එක් පෙට්ටියක දොඩම් 7ක් තිබේ. පෙට...",Sri Lanka,Sri Lankan National,Sri Lankan,Sinhala,1. Number Concept : Identify the place value o...
11,3,9. Mathematical Operations : Divide a number n...,"{""question"": ""කේක් ගෙඩියක් කෑලි 8කට කපා ඇත. අන...","{""question"": ""ශාන්ති සතුව පොල් ගෙඩි 47ක් ඇත. ඇ...","{""question"": ""ඇපල් 7ක් මිතුරන් දෙදෙනෙකු අතර සම...","{""question"": ""කූඩයේ අඹ ගෙඩි 8ක් ඇත. ඒවා රාජා ස...","{""question"": ""පොත් 14ක් සිසුන් දෙදෙනෙකුට සමානව...","{""question"": ""බඳුනක බිස්කට් 10ක් ඇත. ඒවා දරුවන...","{""question"": ""බෑගයක පැන්සල් 13ක් ඇත. මිතුරන් ද...","{""question"": ""බැලූන් 14ක් දරුවන් දෙදෙනෙකු අතර ...","{""question"": ""ටිකිරි සතුව සිප්පි කටු 20ක් ඇත. ...","{""question"": ""කඩයක පලතුරු යුෂ බෝතල් 18ක් ඇත. ඒ...",Sri Lanka,Sri Lankan National,Sri Lankan,Sinhala,1. Number Concept : Identify the place value o...
12,4,1. Number Concept : Identify the place value o...,"{""question"": ""දහස්ථානය 4, සියයස්ථානය 0, දහයස්ථ...","{""question"": ""9103 යන සංඛ්‍යාවේ 9 හි ස්ථානීය අ...","{""question"": ""5682 යන සංඛ්‍යාවේ 6 පිහිටා ඇත්තේ...","{""question"": ""දහසේ 1ක්, සියයේ 3ක්, දහයේ 7ක් සහ...","{""question"": ""1675 යන සංඛ්‍යාව විහිදුවා ලියන්න...","{""question"": ""3, 5, 7, 9 යන ඉලක්කම් භාවිතයෙන් ...","{""question"": ""7305 යන සංඛ්‍යාවේ දහසේ ඒවා කීයක්...","{""question"": ""1237 යන සංඛ්‍යාවේ 1 හි ස්ථානීය අ...","{""question"": ""දහසේ 1ක්, සියයේ 4ක්, දහයේ 0ක් සහ...","{""question"": ""2345 යන සංඛ්‍යාව විහිදුවා ලියන්න...",Sri Lanka,Sri Lankan National,Sri Lankan,Sinhala,1. Number Concept : Identify the place value o...
13,4,10. Mathematical Operations : Multiply a numbe...,"{""question"": ""\nතෑගි පැකට්ටුවකට පොත් තුනක් දමන...","{""question"": ""පළතුරු වෙළෙන්දෙකු එක් පැකට්ටුවක ...","{""question"": ""එක් කණුවක වෙසක් කූඩු 5ක් එල්ලිය ...","{""question"": ""සෑම ශිෂ්‍යයෙකුටම කොකිස් 3ක් බැගි...","{""question"": ""ක්‍රීඩා උත්සවයක් අතරතුර එක් කණුව...","{""question"": ""එක් කූඩයකට අඹ ගෙඩි 3ක් දමන්නේ නම...","{""question"": ""එක් පැකට්ටුවක කැවුම් 15ක් ඇත. පැ...","{""question"": ""මාලයක් සෑදීමට පබළු 50ක් අවශ්‍ය ව...","{""question"": ""ගෙවතු වගාකරුවෙකු එක් පේළියක රත්ම...","{""question"": ""එක් පෙට්ටියක තල ගුලි 80ක් ඇත. ගු...",Sri Lanka,Sri Lankan National,Sri Lankan,Sinhala,1. Number Concept : Identify the place value o...
14,4,11. Mathematical Operations : Divide a number ...,"{""question"": ""පොල් වත්තක පොල් ගෙඩි 366ක් තිබේ....","{""question"": ""කර්මාන්ත ශාලාවක් සෙල්ලම් කාර් 14...","{""question"": ""පරිත්‍යාගයක් ලෙස සීනි පැකට් 300ක...","{""question"": ""සිසුන් අතර බෙදා හැරීම සඳහා පාසලක...","{""question"": ""පුස්තකාලයක කතන්දර පොත් 168ක් ඇත....","{""question"": ""ගුරුවරයෙකු ළඟ ටීක් බෝල 243ක් ඇති...","{""question"": ""ගොවියෙකු බිත්තර 124ක් එකතු කර බි...","{""question"": ""සරුංගල් 216ක් ඇත. ඒවා පන්ති 3ක් ...","{""question"": ""සිල්ලර වෙළඳසැලක කෙසෙල් ගෙඩි 152ක...","{""question"": ""ළමුන් 228 දෙනෙකුගෙන් යුත් කණ්ඩාය...",Sri Lanka,Sri Lankan National,Sri Lankan,Sinhala,1. Number Concept : Identify the place value o...
15,4,12. Measurements : Solve basic problems involv...,"{""question"": ""පීත්ත පටියක දිග 9m 60cm කි. පීත...","{""question"": ""වැට කොටසක් සෙන්ටිමීටර 460ක් උස ය...","{""question"": ""නිවසක බිත්තියක් මීටර් 5ක් උස ය. ...","{""question"": ""පූජාගේ උස සෙන්ටිමීටර 160කි. පූජා...","{""question"": ""මේසයක් සෙන්ටිමීටර 300ක් දිග ය. ම...","{""question"": ""කඹයක් මීටර් 7යි සෙන්ටිමීටර 25ක් ...","{""question"": ""පන්ති කාමරයේ කළු ලෑල්ල සෙන්ටිමීට...","{""question"": ""රාණි මීටර් 5යි සෙන්ටිමීටර 80ක් ඇ...","{""question"": ""දම්වැලක් සෙන්ටිමීටර 245ක් දිග ය....","{""question"": ""දැව පුවරුවක දිග මීටර් 3යි සෙන්ටි...",Sri Lanka,Sri Lankan National,Sri Lankan,Sinhala,1. Number Concept : Identify the place value o...
16,4,13. Measurements : Perform addition and subtra...,"{""question"": ""කලා හා අත්කම් පන්තිය සඳහා සිසුන්...","{""question"": ""ලණුවක් සෙන්ටිමීටර 280ක් දිග ය. ස...","{""question"": ""දොර රෙදි සඳහා රෙදි මීටර් 11ක් ද,...","{""question"": ""පෙදරේරුවෙකු විසින් පළමු දිනයේ ඉද...","{""question"": ""මීටර් 5ක් දිග රිබන් පටියකින් මීට...","{""question"": ""රාධා මීටර් 3යි සෙන්ටිමීටර 15ක දු...","{""question"": ""ෆාතිමා ඇගේ කොණ්ඩයෙන් සෙන්ටිමීටර ...","{""question"": ""කම්බි කැබැල්ලක් මීටර් 4යි සෙන්ටි...","{""question"": ""පොත් රාක්කයක් සෙන්ටිමීටර 150ක් උ...","{""question"": ""රිබන් රෝලක මීටර් 6යි සෙන්ටිමීටර ...",Sri Lanka,Sri Lankan National,Sri Lankan,Sinhala,1. Number Concept : Identify the place value o...
17,4,14. Measurements : Solve basic problems involv...,"{""question"": ""වට්ටක්කා ගෙඩියක බර ග්‍රෑම් 1100 ...","{""question"": ""හාල් පැකට්ටුවක බර ග්‍රෑම් 750ක් ...","{""question"": ""රියන්ති ළඟ ඇති අර්තාපල් මල්ලක බර...","{""question"": ""දරුවෙකුගේ බර කිලෝග්‍රෑම් 5කි. දර...","{""question"": ""කොමඩු ගෙඩියක බර කිලෝග්‍රෑම් 1යි ...","{""question"": ""පාසල් ආපන ශාලාවක් ග්‍රෑම් 6000ක ...","{""question"": ""හාල් මල්ලක බර කිලෝග්‍රෑම් 3කි. එ...","{""question"": ""පේර පෙට්ටියක බර ග්‍රෑම් 2,450කි....","{""question"": ""පාර්සලයක බර කිලෝග්‍රෑම් 3යි ග්‍ර...","{""question"": ""කොමඩු ගෙඩියක බර ග්‍රෑම් 4,200කි....",Sri Lanka,Sri Lankan National,Sri Lankan,Sinhala,1. Number Concept : Identify the place value o...
18,4,15. Measurements : Perform addition and subtra...,"{""question"": ""\nඅම්මා එළවළු වෙළඳපොළෙන් බතල 2kg...","{""question"": ""සඳුනිගේ පාසල් බෑගයේ බර කිලෝග්‍රෑ...","{""question"": ""ප්‍රකාශ් ළඟ සහල් පැකට් දෙකක් ඇති...","{""question"": ""කඩයක කිලෝග්‍රෑම් 1ක පඩියක්, කිලෝ...","{""question"": ""වෙළඳසැලක් සඳුදා දින පරිප්පු කිලෝ...","{""question"": ""පළතුරු වෙළෙන්දෙකු ළඟ කෙසෙල් කිලෝ...","{""question"": ""ධීවරයෙක් සඳුදා දින මාළු කිලෝග්‍ර...","{""question"": ""පාර්සලයක බර කිලෝග්‍රෑම් 6යි ග්‍ර...","{""question"": ""සිල්ලර වෙළෙන්දෙකු එක් මල්ලක කුරක...","{""question"": ""ගොවියෙකු පිපිඤ්ඤා කිලෝග්‍රෑම් 7ය...",Sri Lanka,Sri Lankan National,Sri Lankan,Sinhala,1. Number Concept : Identify the place value o...
19,4,16. Measurements : Solve basic problems involv...,"{""question"": ""බෝතලයක ජලය 2l 400ml අඩංගු වේ. ජල...","{""question"": ""යුෂ පැකට්ටුවක අඹ යුෂ මිලිලීටර 17...","{""question"": ""නීලා වතුර මිලිලීටර 3500ක් බාල්දි...","{""question"": ""අලියෙක් වතුර මිලිලීටර 5000ක් පාන...","{""question"": ""වෙළඳසැලක් දිනක් තුළ පොල්තෙල් ලීට...","{""question"": ""අම්මා ජෝගුවකට කිරි ලීටර 2යි මිලි...","{""question"": ""පොල්කිරි බෝතලයක මිලිලීටර 1,800ක්...","{""question"": ""A බඳුනෙහි තෙල් ලීටර 3යි මිලිලීටර...","{""question"": ""මාළු ටැංකියක වතුර මිලිලීටර 4,750...","{""question"": ""සිසුන් තිදෙනෙකු වතුර මිලිලීටර 11...",Sri Lanka,Sri Lankan National,Sri Lankan,Sinhala,1. Number Concept : Identify the place value o...
20,4,17. Measurements : Perform addition and subtra...,"{""question"": ""භාජනයක කිරි 1l 500ml ක් තිබුණි....","{""question"": ""නීලුකා මුලින්ම බීකරයකට මිලිලීටර ...","{""question"": ""අම්මා පලතුරු බීමක් සෑදීම සඳහා පල...","{""question"": ""ශීලා රසකැවිලි සෑදීම සඳහා පැණි ලී...","{""question"": ""ජෝගුවක යුෂ ලීටර 2යි මිලිලීටර 250...","{""question"": ""බෝතලයක වතුර මිලිලීටර 1,800ක් තිබ...","{""question"": ""ටැංකියක වතුර ලීටර 5යි මිලිලීටර 4...","{""question"": ""කෝකියෙකු ආහාර පිසීම සඳහා පොල් කි...","{""question"": ""තමාලි නැවුම් කිරි ලීටර 5යි මිලිල...","{""question"": ""බඳුනක පොල් තෙල් ලීටර 4ක් තිබුණි....",Sri Lanka,Sri Lankan National,Sri Lankan,Sinhala,1. Number Concept : Identify the place value o...
21,4,18. Measurements : Identify and use the relati...,"{""question"": ""නිමල් පැය භාගයක් ඇවිද්දේ ය. ඔහු ...","{""question"": ""ව්‍යාපෘතියක් සම්පූර්ණ කිරීමට මින...","{""question"": ""හලීම් පැය 1ක් නිදා ගත්තේය. ඔහු න...","{""question"": ""ගුවන් යානයක් අඛණ්ඩව අඩ දවසක් පිය...","{""question"": ""ඔරලෝසුවේ මිනිත්තු කටුවට එක් ඉලක්...","{""question"": ""ඔරලෝසුවේ පැය කටුවට එක් ඉලක්කමක ස...","{""question"": ""බිත්තියක් ඉදිකිරීමට දින 3ක් ගත ව...","{""question"": ""සතියකට දින 7ක් ඇත. සති 3ක ඇති දි...","{""question"": ""කාටූන් චිත්‍රපටයක් පැය 2ක් පවතී....","{""question"": ""පුස්තකාලයක් ඉන් ගත් පොත් සති දෙක...",Sri Lanka,Sri Lankan National,Sri Lankan,Sinhala,1. Number Concept : Identify the place value o...
22,4,19. Measurements : Perform basic transactions ...,"{""question"": ""චරිත්ට ඔහුගේ රු. 10 කාසිය රුපියල...","{""question"": ""මීනා ළඟ රුපියල් 150ක් වටිනා නෝට්...","{""question"": ""කළුම්ට ඔහු සතු 25 සතයේ කාසි අට ස...","{""question"": ""හකීම් ළඟ රුපියලේ කාසි සහ සත 50 ක...","{""question"": ""රූබාට රුපියල් 15.25ක් කාසි තුනක්...","{""question"": ""පසුම්බියක රුපියල් 70ක මුළු වටිනා...","{""question"": ""සුදම්ට පොතක් සඳහා රුපියල් 30ක් ග...","{""question"": ""ෆාතිමාට රුපියල් 150ක් නෝට්ටු තුන...","{""question"": ""සේවකයෙකුට රුපියල් 500ක් ලැබේ. ඔහ...","{""question"": ""පැන්සලක මිල රුපියල් 45කි. නුවන් ...",Sri Lanka,Sri Lankan National,Sri Lankan,Sinhala,1. Number Concept : Identify the place value o...
23,4,2. Number Concept : Write the number names for...,"{""question"": ""9166 හි සංඛ්‍යා නාමය ලියන්න."", ""...","{""question"": ""පිපෙන කුසුම් පෙර පාසල විසින් නව ...","{""question"": ""කඩ හිමියෙකු සතුව මුළු ටීක් බෝල න...","{""question"": ""ගැමුණු විද්‍යාලයේ සිසුන් 3425ක් ...","{""question"": ""ශ්‍රී ලංකාව නිදහස ලැබුවේ එක් දහස...","{""question"": ""5082 යන සංඛ්‍යාවේ සංඛ්‍යා නාමය ...","{""question"": ""පාසල් පුස්තකාලයේ පොත් 7,436ක් ඇත...","{""question"": ""ගොවියෙකු මේ කන්නයේදී අඹ තුන් දහස...","{""question"": ""කොළඹ සිට යාපනය දක්වා මුළු දුර ප්...","{""question"": ""මෙම වසරේ පන්සලේ උත්සවයක් සඳහා බැ...",Sri Lanka,Sri Lankan National,Sri Lankan,Sinhala,1. Number Concept : Identify the place value o...
24,4,20. Measurements : Solve problems involving th...,"{""question"": ""කුඩයක මිළ රු.455 ක් සහ කෝප්පයක ම...",NaN,"{""question"": ""ශේකර් රුපියල් 10යි සත 50කට පැන්ස...","{""question"": ""සටහන් පොතක මිල රුපියල් 85කි, රූල...","{""question"": ""සුනිමල් රුපියල් 320කට පැන්සල් පෙ...","{""question"": ""මේස් යුගලක මිල රුපියල් 150කි, සප...","{""question"": ""වෙසක් කූඩුවක මිල රුපියල් 380.75ක...","{""question"": ""පෑනක මිල රුපියල් 45කි, මකන කැබැල...","{""question"": ""කොකිස් පැකට්ටුවක මිල රුපියල් 165...","{""question"": ""කතන්දර පොතක මිල රුපියල් 680කි, ස...",Sri Lanka,Sri Lankan National,Sri Lankan,Sinhala,1. Number Concept : Identify the place value o...
25,4,3. Number Concept : Arrange any three numbers ...,"{""question"": ""මැතිවරණයකදී අපේක්ෂකයින් තිදෙනෙකු...","{""question"": ""වෙළඳසැල් තුනක් මාසයක් තුළ විකුණන...","{""question"": ""එක් දිනක කොළඹ, ගාල්ල සහ පොළොන්නර...","{""question"": ""පාසල් තුනක සිටින සිසුන් සංඛ්‍යා ...","{""question"": ""නගර තුනක වාර්තා වූ විදුලි පරිභෝජ...","{""question"": ""දුන්හිඳ, දියලුම සහ බඹරකන්ද යන දි...","{""question"": ""ඕලු, නෙලුම් සහ මානෙල් යන පන්ති ත...","{""question"": ""වතු තුනකින් අස්වනු නෙළන ලද පොල් ...","{""question"": ""කියවීමේ තරඟයක් සඳහා පන්ති තුනක ස...","{""question"": ""දින තුනක දී දුම්රියෙන් ගමන් කළ ම...",Sri Lanka,Sri Lankan National,Sri Lankan,Sinhala,1. Number Concept : Identify the place value o...
26,4,4. Number Concept : Identify the greatest or s...,"{""question"": ""වීඩියෝ ක්‍රීඩාවකදී සුමල් ලකුණු 6...","{""question"": ""8, 2, 4, 5 යන ඉලක්කම් භාවිතයෙන් ...","{""question"": ""5, 7, 1, 8 යන ඉලක්කම් (එක් වරක් ...","{""question"": ""ධාවන තරගයකදී නිමල් මීටර් 4,235ක්...","{""question"": ""වෙළඳසැල් තුනක් ඒවායේ සතියක ආදායම...","{""question"": ""අක්ෂර වින්‍යාස තරගයකදී තරිනි ලකු...","{""question"": ""3, 9, 1, 4 යන ඉලක්කම් (එක් වරක් ...","{""question"": ""පිදුරුතලාගල කන්දේ උස මීටර් 2524ක...","{""question"": ""ගොවියෙකු පොල් වතු තුනකින් පහත සඳ...","{""question"": ""2, 9, 8, 4 යන ඉලක්කම් භාවිතයෙන් ...",Sri Lanka,Sri Lankan National,Sri Lankan,Sinhala,1. Number Concept : Identify the place value o...
27,4,5. Number Concept : Construct number sequences...,"{""question"": ""නිමාලි පොතක් කියවන්න පටන් ගත්තා ...","{""question"": ""නිෂා පළමු පේළියේ කොඩි 18ක් ද, දෙ...","{""question"": ""කමල් පළමු දිනයේ පැල 9ක් ද, දෙවන ...","{""question"": ""පළමු දිනයේ ගසක කපුටන් 14ක් ද, දෙ...","{""question"": ""රටාව හඳුනාගෙන හිස්තැන් පුරවන්න: ...","{""question"": ""පැහැසරා විහාරයේ පහන් දල්වයි. ඇය ...","{""question"": ""පහත සංඛ්‍යා රටාවේ ඊළඟ සංඛ්‍යා දෙ...","{""question"": ""මහේෂ්වරී විවිධ දිග ඇති මල් මාලා ...","{""question"": ""පහත සංඛ්‍යා රටාවේ හිස්තැන් පුරවන...","{""question"": ""පහත සංඛ්‍යා රටාවේ හිස්තැන් වලට ආ...",Sri Lanka,Sri Lankan National,Sri Lankan,Sinhala,1. Number Concept : Identify the place value o...

In [28]:
print(examples_wide.iloc[40]["topic_list"])

1. Numbers : Identify the place value of digits in numbers up to the ten-thousands place
10. Mathematical Operations : Subtract one number from another, each up to four digits, using borrowing where necessary
11. Mathematical Operations : Multiply a number up to three digits by a number between 2 and 10
12. Mathematical Operations : Divide a number up to three digits by a number between 2 and 10
13. Mathematical Operations : Solve simple problems involving addition and subtraction
14. Mathematical Operations : Solve simple problems involving multiplication and division
15. Measurements : Solve problems involving kilometres and metres
16. Measurements : Solve simple calculation problems involving meters and centimetres
17. Measurements : Solve basic problems involving the mass of objects
18. Measurements : Solve basic problems involving volume and capacity
19. Measurements : Solve problems involving calculations of the passage of time, including hours and minutes
2. Numbers : Write the number names for numbers up to 100,000 and convert number names back to numerals
20. Money : Perform simple money-related calculations using the four basic arithmetic operations
21. Money : Solve problems involving bills
3. Numbers : Arrange any three numbers up to 99,999
4. Numbers : Construct number sequences with the common difference ranging from 2 to 10
5. Numbers : Construct number sequences with the common ratio ranging from 2 to 10
6. Numbers : Represent halves, quarters, and tenths as parts of a whole and as parts of a set of objects
7. Numbers : Recognize and use Roman numerals up to twenty
8. Numbers : Recognize tenths in the decimal form and use them
9. Mathematical Operations : Add numbers that have up to four digits, with carry-over

In [ ]:
examples_wide.columns.name = None

sinhala_df = sinhala_df.merge(
    examples_wide,
    on=["grade", "topic"],
    how="left"
)